/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Seguros_app;

import java.awt.AWTException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Roland
 */
public class Nuevo extends javax.swing.JPanel {

    /**
     * Creates new form Nuevo
     */
    JOptionPane alerta = new JOptionPane();
    float cotizacion = 0;
    int contador = 0;
    float cotizacion1 = 0;
    int contador1 = 0;

    DefaultTableCellRenderer TablaRenderer = new DefaultTableCellRenderer();
    ArrayList<Integer> Columna6 = new ArrayList();
    ArrayList<Integer> Columna5 = new ArrayList();
    ArrayList<String> Columna4 = new ArrayList();
    ArrayList<String> Columna8 = new ArrayList();
    ArrayList<String> fila7 = new ArrayList();

    public Nuevo(JFrame x) {
       
        initComponents();
        TablaRenderer.setHorizontalAlignment(SwingConstants.CENTER); // aqui defines donde alinear
        for (int i = 1; i < 9; i++) {
            Tabla.getColumnModel().getColumn(i).setCellRenderer(TablaRenderer);
        }
        Tabla.setRowHeight(25);
        for (int j = 0; j < 7; j++) {
            Columna6.add(j, 0);
            Columna5.add(j, 0);
            Columna4.add(j, "");
            Columna8.add(j, "");
        }
        for (int j = 0; j < 9; j++) {
            fila7.add(j, "");
        }
     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Titular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        Cotizacion_Input = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Contingencia = new javax.swing.JLabel();
        Bruto_Anu = new javax.swing.JLabel();
        Enfermedades = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Selector = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        Direccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Selector1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        Edad1 = new javax.swing.JLabel();
        Enfermedades1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Direccion1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Titular1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Cotizacion_Input1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Bruto_Anu1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Contingencia1 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        Capturar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        EdadHijo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Hipoteca_sobreIngresos = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        nHijos = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(2203, 811));
        setMinimumSize(new java.awt.Dimension(830, 811));
        setName("2 Personas"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel1.setText("Titular");

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel3.setText("Base Cotización 2022");

        jCheckBox2.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jCheckBox2.setText("Moto");

        jCheckBox1.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jCheckBox1.setText("Fuma");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        Cotizacion_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Cotizacion_InputKeyReleased(evt);
            }
        });

        jLabel5.setText("Salario Bruto Anual:");

        jLabel6.setText("Coste Contingencia Comunes:");

        Contingencia.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N

        Bruto_Anu.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel4.setText("Enfermedades");

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel7.setText("Fecha de Nacimiento");

        Selector.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                SelectorPropertyChange(evt);
            }
        });

        jLabel8.setText("Edad:");

        Edad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                EdadPropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel2.setText("Dirección");

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel9.setText("Fecha de Nacimiento");

        Selector1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Selector1PropertyChange(evt);
            }
        });

        jLabel10.setText("Edad:");

        Edad1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Edad1PropertyChange(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel11.setText("Enfermedades");

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel12.setText("Dirección");

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel13.setText("Titular");

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel14.setText("Base Cotización 2022");

        Cotizacion_Input1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Cotizacion_Input1KeyReleased(evt);
            }
        });

        jLabel15.setText("Salario Bruto Anual:");

        Bruto_Anu1.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N

        jLabel16.setText("Coste Contingencia Comunes:");

        Contingencia1.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N

        jCheckBox3.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jCheckBox3.setText("Moto");

        jCheckBox4.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jCheckBox4.setText("Fuma");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        Capturar.setText("Capturar");
        Capturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapturarActionPerformed(evt);
            }
        });

        jLabel17.setText("% de Hipotecas sobre ingresos:");

        jLabel18.setText("Vencimiento:");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jLabel19.setText("Cuota mensual");

        jLabel20.setText("Prestamos");

        EdadHijo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EdadHijoKeyReleased(evt);
            }
        });

        jLabel21.setText("Edad media hijos cotizante < 25");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contingencias comunes", "Pago anual SS", "Perdida Salario anual", "Prevision Reservas", "Valor recomendado", "Coste anual de cobertura", "Suma Anual Coberturas", "Coste mensual", "Nº Proyecto", "% Salario mes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TablaPropertyChange(evt);
            }
        });
        Tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TablaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setMinWidth(305);
            Tabla.getColumnModel().getColumn(1).setPreferredWidth(120);
            Tabla.getColumnModel().getColumn(5).setPreferredWidth(110);
            Tabla.getColumnModel().getColumn(6).setPreferredWidth(110);
        }

        jLabel22.setText("Nº Hijos:");

        nHijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nHijosActionPerformed(evt);
            }
        });
        nHijos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nHijosKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(445, 445, 445)
                                .addComponent(Cotizacion_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(394, 394, 394)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bruto_Anu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Contingencia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(358, 358, 358)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Titular, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(275, 275, 275)
                                        .addComponent(jCheckBox2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBox1))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(Selector, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Enfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(445, 445, 445)
                                .addComponent(Cotizacion_Input1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(Direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Enfermedades1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(394, 394, 394)
                                        .addComponent(jLabel16)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bruto_Anu1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Contingencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(660, 660, 660)
                                        .addComponent(Capturar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(Titular1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(257, 257, 257)
                                        .addComponent(jCheckBox3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBox4))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1565, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(Selector1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(EdadHijo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel19)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Hipoteca_sobreIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(524, 605, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Titular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cotizacion_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Enfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bruto_Anu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Contingencia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Selector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Titular1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cotizacion_Input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Enfermedades1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bruto_Anu1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Contingencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Capturar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Selector1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(Edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdadHijo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hipoteca_sobreIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EdadHijo, Hipoteca_sobreIngresos, jLabel17, jLabel18, jLabel19, jLabel20, jLabel21, jTextField2, jTextField3, jTextField4});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Direccion, Direccion1, Enfermedades, Enfermedades1, Titular, Titular1, jLabel1, jLabel11, jLabel12, jLabel13, jLabel2, jLabel4});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Edad1, Selector, Selector1, jLabel10, jLabel22, jLabel9, nHijos});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Bruto_Anu, Bruto_Anu1, Contingencia, Contingencia1});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Cotizacion_Input, Cotizacion_Input1});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel15, jLabel16});

    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void Cotizacion_InputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cotizacion_InputKeyReleased

        try {
            this.cotizacion = parseFloat(Cotizacion_Input.getText());
        } catch (Exception ex) {
            if (ex.toString().equals("java.lang.NumberFormatException: empty String")) {
            } else {
                alerta.showMessageDialog(null, "Cotización solo admite valores númericos" + "\n\n" + "Codigo del error: " + ex);
            }
        }

        Recargar();
    }//GEN-LAST:event_Cotizacion_InputKeyReleased
    public void Recargar() {

        int contin_redondeado = Math.round(this.cotizacion * (float) 0.047);

        Contingencia.setText("" + contin_redondeado);
        Bruto_Anu.setText("" + (int) this.cotizacion * 12);
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();

        ActualizarTabla(model);
    }

    public void Recargar1() {

        int contin_redondeado = Math.round(this.cotizacion1 * (float) 0.047);

        Contingencia1.setText("" + contin_redondeado);
        Bruto_Anu1.setText("" + (int) this.cotizacion1 * 12);

        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();

        ActualizarTabla(model);

    }
    private void SelectorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_SelectorPropertyChange
        int mes;
        int dia;
        int anio;

        if (contador >= 1) {

            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy", Locale.ENGLISH);
            Date firstDate;
            try {
                mes = Selector.getDate().getMonth() + 1;
                dia = Selector.getDate().getDay();
                anio = Selector.getDate().getYear() + 1900;
                firstDate = sdf.parse(mes + "/" + dia + "/" + anio);

                Date secondDate = new Date();

                long diff = secondDate.getTime() - firstDate.getTime();

                TimeUnit time = TimeUnit.DAYS;
                long diffrence = time.convert(diff, TimeUnit.MILLISECONDS) + 1;
                if (diffrence / 365 < 18) {
                    Edad.setForeground(Color.red);
                } else {
                    Edad.setForeground(Color.black);
                }
                Edad.setText("" + diffrence / 365);

            } catch (ParseException ex) {
                alerta.showMessageDialog(null, "Algo no ha ido bien con la fecha" + ex);

            }
        }
        contador++;
    }//GEN-LAST:event_SelectorPropertyChange

    private void Selector1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Selector1PropertyChange
        int mes;
        int dia;
        int anio;

        if (contador1 >= 1) {

            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy", Locale.ENGLISH);
            Date firstDate;
            try {
                mes = Selector1.getDate().getMonth() + 1;
                dia = Selector1.getDate().getDay();
                anio = Selector1.getDate().getYear() + 1900;
                firstDate = sdf.parse(mes + "/" + dia + "/" + anio);

                Date secondDate = new Date();

                long diff = secondDate.getTime() - firstDate.getTime();

                TimeUnit time = TimeUnit.DAYS;
                long diffrence = time.convert(diff, TimeUnit.MILLISECONDS) + 1;
                if (diffrence / 365 < 18) {
                    Edad1.setForeground(Color.red);
                } else {
                    Edad1.setForeground(Color.black);
                }
                Edad1.setText("" + diffrence / 365);

            } catch (ParseException ex) {
                alerta.showMessageDialog(null, "Algo no ha ido bien con la fecha" + ex);

            }
        }
        contador1++;
    }//GEN-LAST:event_Selector1PropertyChange

    private void Cotizacion_Input1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cotizacion_Input1KeyReleased
        try {
            this.cotizacion1 = parseFloat(Cotizacion_Input1.getText());
        } catch (Exception ex) {
            if (ex.toString().equals("java.lang.NumberFormatException: empty String")) {
            } else {
                alerta.showMessageDialog(null, "Cotización solo admite valores númericos" + "\n\n" + "Codigo del error: " + ex);
            }
        }

        Recargar1();
    }//GEN-LAST:event_Cotizacion_Input1KeyReleased

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed
    public void ActualizarTabla(DefaultTableModel model) {

        DecimalFormat df = new DecimalFormat("###.##");
        if (Tabla.getRowCount() > 0) {
            int i = 6;
            while (Tabla.getRowCount() > 0) { //borramos filas y actualizamos

                model.removeRow(i);
                i--;
            }
        }
        int edadhijo;
        int realedadhijo;
        try {
            int numerohijos = 0;
            float porcentaje = 0;
            if (!nHijos.getText().equals("")) {
                numerohijos = parseInt(nHijos.getText());
                if (numerohijos > 2) {
                    porcentaje = 1;

                } else if (numerohijos > 0) {

                    porcentaje = ((float) 0.20 * numerohijos) + (float) 0.52;
                }
            }
            int viudedad_orfandad_1_hijo = Math.round((cotizacion * (float) 0.85) * 14 * porcentaje);
            int viudedad_52 = Math.round((cotizacion * (float) 0.85) * 14 * (float) 0.52);
            //2ª COLUMNA TABLA
            int Perdida = viudedad_orfandad_1_hijo - parseInt(Bruto_Anu.getText());
            int Perdida2 = viudedad_52 - parseInt(Bruto_Anu.getText());
            int perdida3 = (int) ((cotizacion * (float) 0.85) * 14) - parseInt(Bruto_Anu.getText());
            int perdida4 = (int) (((cotizacion * 0.85) * 0.55) * 14) - parseInt(Bruto_Anu.getText());
            int perdida5 = (int) (((cotizacion * 0.85) * 0.75) * 12) - parseInt(Bruto_Anu.getText());
            int perdida6 = (int) (((cotizacion * 0.85) * 0.75) * 14) - parseInt(Bruto_Anu.getText());

            if (EdadHijo.getText().equals("")) {
                edadhijo = 0;
                realedadhijo = 0;
            } else {
                edadhijo = (25 - parseInt(EdadHijo.getText())) * Perdida;
                realedadhijo = parseInt(EdadHijo.getText());
            }
            int previ2 = 0;
            int edad_conyuge = 0;
            if (!Edad1.getText().equals("")) {
                previ2 = ((67 - (parseInt(Edad1.getText())) + (25 - realedadhijo)) * Perdida2);
                edad_conyuge = parseInt(Edad1.getText());
            }
            int previ3 = 0;
            int edad = 0;
            if (!Edad.getText().equals("")) {
                previ3 = ((67 - parseInt(Edad.getText())) * perdida3);
                edad = parseInt(Edad.getText());
            }

            model.addRow(new String[]{"Viudedad + Orfandad hijo/os < 25", "" + viudedad_orfandad_1_hijo + "€", "" + Perdida + "€", "" + edadhijo + "€", Columna4.get(0), Columna5.get(0) + "€", Columna6.get(0) + "€", df.format(Columna6.get(0) / 12.0) + "€", Columna8.get(0), df.format((((Columna6.get(0) / 12.0)) * 100) / cotizacion) + "%"});
            model.addRow(new String[]{"Viudedad(52%)", viudedad_52 + "€", Perdida2 + "€", previ2 + "€", Columna4.get(1), Columna5.get(1) + "€", Columna6.get(1) + "€", df.format(Columna6.get(1) / 12.0) + "€", Columna8.get(1), df.format((((Columna6.get(1) / 12.0)) * 100) / cotizacion) + "%"});
            model.addRow(new String[]{"Invalidez Absoluta Permanente(100%)", "" + ((int) (cotizacion * (float) 0.85) * 14) + "€", perdida3 + "€", previ3 + "€", Columna4.get(2), Columna5.get(2) + "€", Columna6.get(2) + "€", df.format(Columna6.get(2) / 12.0) + "€", Columna8.get(2), df.format((((Columna6.get(2) / 12.0)) * 100) / cotizacion) + "%"});
            model.addRow(new String[]{"Incap. Pmte(55%)+20% >50 años dificultad otros empleos", (int) (((cotizacion * 0.85) * 0.55) * 14) + "€", perdida4 + "€", (67 - edad) * perdida4 + "€", Columna4.get(3), Columna5.get(3) + "€", Columna6.get(3) + "€", df.format(Columna6.get(3) / 12.0) + "€", Columna8.get(3), df.format((((Columna6.get(3) / 12.0)) * 100) / cotizacion) + "%"});
            model.addRow(new String[]{"Incap. Temporal(75% al dia 21)", (int) (((cotizacion * 0.85) * 0.75) * 12) + "€", perdida5 + "€", df.format((float) perdida5 / 365) + "€", Columna4.get(4), Columna5.get(4) + "€", Columna6.get(4) + "€", df.format(Columna6.get(4) / 12.0) + "€", Columna8.get(4), df.format((((Columna6.get(4) / 12.0)) * 100) / cotizacion) + "%"});
            model.addRow(new String[]{"Jubilación de 67 a 85 años.Cotizando min 15 años(Ver tabla)", (int) (((cotizacion * 0.85) * 0.75) * 14) + "€", perdida6 + "€", (85 - 67) * perdida6 + "€", Columna4.get(5), Columna5.get(5) + "€", Columna6.get(5) + "€", df.format(Columna6.get(5) / 12.0) + "€", Columna8.get(5), df.format((((Columna6.get(5) / 12.0)) * 100) / cotizacion) + "%"});
            model.addRow(new String[]{fila7.get(0), fila7.get(1), fila7.get(2), fila7.get(3), Columna4.get(6), Columna5.get(6) + "€", Columna6.get(6) + "€", df.format(Columna6.get(6) / 12.0) + "€", Columna8.get(6), df.format((((Columna6.get(6) / 12.0)) * 100) / cotizacion) + "%"});

        } catch (Exception ex) {
            // System.out.println(ex);
        }

    }
    private void CapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapturarActionPerformed

        Dimension screenSize = Nuevo.super.getSize();
        //Rectangle screenRectangle = new Rectangle(screenSize);
        Rectangle screenRectangle = new Rectangle(Nuevo.this.getLocationOnScreen(), Nuevo.super.getSize());

        Robot robot;
        try {
            robot = new Robot();

            BufferedImage image = robot.createScreenCapture(screenRectangle);
            ImageIO.write(image, "png", new File(Titular.getText() + "-" + Titular1.getText() + ".png"));
        } catch (Exception ex) {
            Logger.getLogger(Nuevo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_CapturarActionPerformed

    private void TablaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TablaPropertyChange
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
        try {

            if (Tabla.getModel().getRowCount() > 0) {

                for (int i = 0; i < 6; i++) {        //Ponemos 0 en los que no esten rellenados aún.

                    if (((String) model.getValueAt(i, 5)).equals("")) {
                        model.setValueAt(0 + "", i, 5);
                    }
                }

                for (int j = 0; j < 7; j++) { // quitar simbolo de €
                    String s = "";
                    s = (String) model.getValueAt(j, 5);
                    s = s.replace("€", "");
                    Columna5.set(j, parseInt(s));
                    if (!((String) model.getValueAt(j, 4)).equals("")) {

                        Columna4.set(j, (String) model.getValueAt(j, 4));
                    }
                    if (!((String) model.getValueAt(j, 8)).equals("")) {
                        Columna8.set(j, (String) model.getValueAt(j, 8));
                    }
                }
                for (int j = 0; j < 9; j++) {
                    if (!((String) model.getValueAt(6, j)).equals("")) {

                        fila7.set(j, (String) model.getValueAt(6, j));
                    }
                }

                Columna6.set(0, Columna5.get(0));
                Columna6.set(1, Columna5.get(0) + Columna5.get(1));
                Columna6.set(2, Columna5.get(0) + Columna5.get(1) + Columna5.get(2));
                Columna6.set(3, Columna5.get(0) + Columna5.get(1) + Columna5.get(2) + Columna5.get(4));
                Columna6.set(4, Columna5.get(0) + Columna5.get(1) + Columna5.get(2) + Columna5.get(3) + Columna5.get(4));
                Columna6.set(5, Columna5.get(0) + Columna5.get(1) + Columna5.get(2) + Columna5.get(3) + Columna5.get(4) + Columna5.get(5));
                Columna6.set(6, Columna5.get(0) + Columna5.get(1) + Columna5.get(2) + Columna5.get(3) + Columna5.get(4) + Columna5.get(5) + Columna5.get(6));

            }
        } catch (Exception ex) {
            alerta.showMessageDialog(null, " \n\n Error:" + ex);
        }
        ActualizarTabla(model);
    }//GEN-LAST:event_TablaPropertyChange

    private void TablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaKeyReleased

    }//GEN-LAST:event_TablaKeyReleased

    private void EdadHijoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EdadHijoKeyReleased
        Recargar();
    }//GEN-LAST:event_EdadHijoKeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased

        DecimalFormat df = new DecimalFormat("###.##");

        if (!jTextField3.getText().equals("")) {
            String s;
            s = jTextField3.getText();
            s = s.replaceAll("€", "");
            float cuotamensual = parseFloat(s);
            Hipoteca_sobreIngresos.setText(df.format(cuotamensual * 100 / (cotizacion + cotizacion1)) + "%");
        }

    }//GEN-LAST:event_jTextField3KeyReleased

    private void EdadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_EdadPropertyChange
        Recargar();
    }//GEN-LAST:event_EdadPropertyChange

    private void Edad1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Edad1PropertyChange
        Recargar();
    }//GEN-LAST:event_Edad1PropertyChange

    private void nHijosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nHijosKeyReleased
        Recargar();
    }//GEN-LAST:event_nHijosKeyReleased

    private void nHijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nHijosActionPerformed
        Recargar();
    }//GEN-LAST:event_nHijosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bruto_Anu;
    private javax.swing.JLabel Bruto_Anu1;
    private javax.swing.JButton Capturar;
    private javax.swing.JLabel Contingencia;
    private javax.swing.JLabel Contingencia1;
    private javax.swing.JTextField Cotizacion_Input;
    private javax.swing.JTextField Cotizacion_Input1;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Direccion1;
    private javax.swing.JLabel Edad;
    private javax.swing.JLabel Edad1;
    private javax.swing.JTextField EdadHijo;
    private javax.swing.JTextField Enfermedades;
    private javax.swing.JTextField Enfermedades1;
    private javax.swing.JLabel Hipoteca_sobreIngresos;
    private com.toedter.calendar.JDateChooser Selector;
    private com.toedter.calendar.JDateChooser Selector1;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField Titular;
    private javax.swing.JTextField Titular1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField nHijos;
    // End of variables declaration//GEN-END:variables
}
